-- Restore all missing speakers from original dataset
INSERT INTO speakers (name, slug, title, bio, expertise, location, overall_rating, review_count, image_url, verified, featured, category, achievements, lectures, email, phone, website, languages, speaker_type, fee, hide_profile, hide_ratings, hide_social, hide_contact) VALUES 

('Dr. Kostas Chochlidakis', 'kostaschochlidakis', 'Chair, Department of Prosthodontics - Tufts University', 'Dr. Kostas Chochlidakis is Chair and Associate Professor at Tufts University School of Dental Medicine, Department of Prosthodontics', ARRAY['Prosthodontics', 'Digital Dentistry', 'Implant Dentistry'], 'Boston, MA', 4.95, 142, '/attached_assets/straumann_speakers/FAF-Kostas-Chochlidakis.png', true, true, 'Prosthodontics', ARRAY['Chair - Department of Prosthodontics', 'Tufts University Professor'], ARRAY['Digital Prosthodontics', 'Implant-Supported Restorations'], 'kchochlidakis@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English', 'Greek'], 'academic', '9000', false, false, false, false),

('Dr. Edmond Bedrossian', 'edmondbedrossian', 'Oral & Maxillofacial Surgeon - Zygomatic Implant Specialist', 'Dr. Edmond Bedrossian is a board-certified oral and maxillofacial surgeon specializing in zygomatic implants and complex rehabilitation', ARRAY['Oral Surgery', 'Zygomatic Implants', 'Complex Rehabilitation'], 'San Francisco, CA', 4.97, 203, '/attached_assets/straumann_speakers/FAF-Edmond-Bedrossian.png', true, true, 'Oral Surgery', ARRAY['Zygomatic Implant Pioneer', 'Complex Rehabilitation Expert'], ARRAY['Zygomatic Implant Techniques', 'Complex Maxillofacial Surgery'], 'ebedrossian@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English'], 'clinical', '12000', false, false, false, false),

('Dr. Ghida Lawand', 'ghidalawand', 'Prosthodontist - Digital Dentistry Expert', 'Dr. Ghida Lawand is a prosthodontist specializing in digital dentistry and implant-supported restorations', ARRAY['Prosthodontics', 'Digital Dentistry', 'Implant Restorations'], 'Lebanon', 4.91, 87, '/attached_assets/straumann_speakers/FAF-Ghida-Lawand.png', true, false, 'Prosthodontics', ARRAY['Digital Dentistry Specialist', 'Implant Restoration Expert'], ARRAY['Digital Prosthodontics', 'CAD/CAM Technology'], 'glawand@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English', 'Arabic'], 'clinical', '8000', false, false, false, false),

('Dr. Eric Van Dooren', 'ericvandooren', 'Oral Surgeon & Implantologist', 'Dr. Eric Van Dooren is an internationally recognized oral surgeon and implantologist', ARRAY['Oral Surgery', 'Implantology', 'Bone Augmentation'], 'Belgium', 4.93, 156, '/attached_assets/straumann_speakers/FAF-Eric-Van-Dooren.png', true, false, 'Oral Surgery', ARRAY['International Implant Expert', 'Bone Augmentation Specialist'], ARRAY['Advanced Implant Surgery', 'Bone Grafting Techniques'], 'evandooren@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English', 'Dutch', 'French'], 'clinical', '10000', false, false, false, false),

('Dr. Maurício Araújo', 'mauricioaraujo', 'Periodontist - University of São Paulo', 'Dr. Maurício Araújo is a renowned periodontist and professor at the University of São Paulo', ARRAY['Periodontics', 'Implant Dentistry', 'Tissue Regeneration'], 'São Paulo, Brazil', 4.96, 178, '/attached_assets/straumann_speakers/FAF-Mauricio-Araujo.png', true, false, 'Periodontics', ARRAY['University Professor', 'Tissue Regeneration Expert'], ARRAY['Periodontal Regeneration', 'Implant Site Development'], 'maraujo@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['Portuguese', 'English'], 'academic', '8500', false, false, false, false),

('Dr. Fouad Khoury', 'fouadkhoury', 'Oral & Maxillofacial Surgeon', 'Dr. Fouad Khoury is a specialist in oral and maxillofacial surgery with expertise in complex implant procedures', ARRAY['Oral Surgery', 'Maxillofacial Surgery', 'Complex Implants'], 'Germany', 4.94, 134, '/attached_assets/straumann_speakers/FAF-Fouad-Khoury.png', true, false, 'Oral Surgery', ARRAY['Maxillofacial Surgery Expert', 'Complex Implant Specialist'], ARRAY['Advanced Maxillofacial Surgery', 'Complex Implant Placement'], 'fkhoury@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['German', 'English', 'Arabic'], 'clinical', '9500', false, false, false, false),

('Dr. Hilt Tatum', 'hilttatum', 'Oral & Maxillofacial Surgeon', 'Dr. Hilt Tatum is an oral and maxillofacial surgeon specializing in reconstructive surgery', ARRAY['Oral Surgery', 'Reconstructive Surgery', 'Trauma Surgery'], 'United States', 4.92, 167, '/attached_assets/straumann_speakers/FAF-Hilt-Tatum.png', true, false, 'Oral Surgery', ARRAY['Reconstructive Surgery Expert', 'Trauma Surgery Specialist'], ARRAY['Reconstructive Techniques', 'Trauma Management'], 'htatum@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English'], 'clinical', '11000', false, false, false, false),

('Dr. Lyndon Cooper', 'lyndoncooper', 'Prosthodontist - University of Illinois', 'Dr. Lyndon Cooper is a prosthodontist and professor specializing in implant dentistry', ARRAY['Prosthodontics', 'Implant Dentistry', 'Oral Rehabilitation'], 'Chicago, IL', 4.93, 145, '/attached_assets/straumann_speakers/FAF-Lyndon-Cooper.png', true, false, 'Prosthodontics', ARRAY['University Professor', 'Implant Dentistry Expert'], ARRAY['Implant Prosthodontics', 'Oral Rehabilitation'], 'lcooper@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['English'], 'academic', '9000', false, false, false, false),

('Dr. Mariano Sanz', 'marianosanz', 'Professor of Periodontology - Complutense University', 'Dr. Mariano Sanz is a professor of periodontology and internationally recognized expert', ARRAY['Periodontics', 'Implant Dentistry', 'Oral Medicine'], 'Madrid, Spain', 4.98, 234, '/attached_assets/straumann_speakers/FAF-Mariano-Sanz.png', true, true, 'Periodontics', ARRAY['University Professor', 'International Expert'], ARRAY['Periodontal Therapy', 'Implant Complications'], 'msanz@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['Spanish', 'English'], 'academic', '12000', false, false, false, false),

('Dr. Massimo Simion', 'massimosimion', 'Oral Surgeon - University of Milan', 'Dr. Massimo Simion is a professor of oral surgery and bone regeneration expert', ARRAY['Oral Surgery', 'Bone Regeneration', 'Implant Surgery'], 'Milan, Italy', 4.95, 189, '/attached_assets/straumann_speakers/FAF-Massimo-Simion.png', true, false, 'Oral Surgery', ARRAY['University Professor', 'Bone Regeneration Expert'], ARRAY['Guided Bone Regeneration', 'Implant Surgery'], 'msimion@devrightspeakers.com', '214-884-4100', 'https://devrightspeakers.com', ARRAY['Italian', 'English'], 'academic', '10500', false, false, false, false)

ON CONFLICT (slug) DO NOTHING;