// Authoritative speaker -> discipline mapping sourced directly from the client's
// spreadsheet ("Speakers by discipline for Sphere"). This is the ground truth for
// which discipline each named speaker belongs to. Applied on every startup
// (idempotent) so it always wins over the best-effort auto-matcher and cannot be
// silently lost to future auto-migration resets or admin bulk actions.
export interface DisciplineSourceRow {
  name: string;
  discipline: string;
}

export const DISCIPLINE_SOURCE_DATA: DisciplineSourceRow[] = [
  { name: "Amanda Cole Hill", discipline: "Dental Hygiene" },
  { name: "Dr. Kayleigh E. Temple", discipline: "Dental Hygiene" },
  { name: "Erin A. O'Neil", discipline: "Dental Hygiene" },
  { name: "Katrina M. Sanders", discipline: "Dental Hygiene" },
  { name: "Kelly Turner", discipline: "Dental Hygiene" },
  { name: "Michelle Strange", discipline: "Dental Hygiene" },
  { name: "Sarah Cottingham", discipline: "Dental Hygiene" },
  { name: "Alexander Wuensche", discipline: "Dental Laboratory - Technician" },
  { name: "Brandon Dickerman", discipline: "Dental Laboratory - Technician" },
  { name: "Charles Banh", discipline: "Dental Laboratory - Technician" },
  { name: "Dr. Jaideep R. Deshpande", discipline: "Dental Laboratory - Technician" },
  { name: "Edward Khalameizer", discipline: "Dental Laboratory - Technician" },
  { name: "Jack Marrano", discipline: "Dental Laboratory - Technician" },
  { name: "Julie Brossoit", discipline: "Dental Laboratory - Technician" },
  { name: "Justin Lai", discipline: "Dental Laboratory - Technician" },
  { name: "Marisa Notturno", discipline: "Dental Laboratory - Technician" },
  { name: "Naoki Hayashi", discipline: "Dental Laboratory - Technician" },
  { name: "Sam Alawie", discipline: "Dental Laboratory - Technician" },
  { name: "Dr. Alan S. Law", discipline: "Endodontics" },
  { name: "Christie Fink", discipline: "General Dentistry" },
  { name: "Dr. Ahmad Kutkut", discipline: "General Dentistry" },
  { name: "Dr. Allison Rascon", discipline: "General Dentistry" },
  { name: "Dr. Anna Singh", discipline: "General Dentistry" },
  { name: "Dr. Bart Silverman", discipline: "General Dentistry" },
  { name: "Dr. Bryan Basom", discipline: "General Dentistry" },
  { name: "Dr. Carter Reeves", discipline: "General Dentistry" },
  { name: "Dr. DeVonte Johnson", discipline: "General Dentistry" },
  { name: "Dr. Diana V. Messadi", discipline: "General Dentistry" },
  { name: "Dr. Hisham Barakat", discipline: "General Dentistry" },
  { name: "Dr. Hongseok An", discipline: "General Dentistry" },
  { name: "Dr. Howard Gluckman", discipline: "General Dentistry" },
  { name: "Dr. James W. Willis", discipline: "General Dentistry" },
  { name: "Dr. Jeff Briney", discipline: "General Dentistry" },
  { name: "Dr. Jeffrey B. Carter", discipline: "General Dentistry" },
  { name: "Dr. Jin Y. Kim", discipline: "General Dentistry" },
  { name: "Dr. John A. Svirsky", discipline: "General Dentistry" },
  { name: "Dr. Jonathan Tsang", discipline: "General Dentistry" },
  { name: "Dr. Likith V. Reddy", discipline: "General Dentistry" },
  { name: "Dr. Louis Kaufman", discipline: "General Dentistry" },
  { name: "Dr. Maria Kunstadter", discipline: "General Dentistry" },
  { name: "Dr. Mariz Tanious", discipline: "General Dentistry" },
  { name: "Dr. Marta Revilla León", discipline: "General Dentistry" },
  { name: "Dr. Matthew Fay", discipline: "General Dentistry" },
  { name: "Dr. Mohamed Wagdy Bissar", discipline: "General Dentistry" },
  { name: "Dr. Peter Rivoli", discipline: "General Dentistry" },
  { name: "Dr. Ron Zokol", discipline: "General Dentistry" },
  { name: "Dr. Sara Knox", discipline: "General Dentistry" },
  { name: "Dr. Sarah Jockin", discipline: "General Dentistry" },
  { name: "Dr. Sergio Bernardes", discipline: "General Dentistry" },
  { name: "Dr. Suheil M. Boutros", discipline: "General Dentistry" },
  { name: "Dr. Walter C. Chitwood Jr.", discipline: "General Dentistry" },
  { name: "Eric Tobler", discipline: "General Dentistry" },
  { name: "Jaideep R. Deshpande", discipline: "General Dentistry" },
  { name: "Jessica Russell", discipline: "General Dentistry" },
  { name: "Joseph Kolligian", discipline: "General Dentistry" },
  { name: "Kalpesh Patel", discipline: "General Dentistry" },
  { name: "Lynda Ricketson", discipline: "General Dentistry" },
  { name: "Michael Wagner", discipline: "General Dentistry" },
  { name: "Minh Tran", discipline: "General Dentistry" },
  { name: "Nick Murray", discipline: "General Dentistry" },
  { name: "Philippe Hujoel", discipline: "General Dentistry" },
  { name: "Raffi Aghvinian", discipline: "General Dentistry" },
  { name: "Slahedinne Zidi", discipline: "General Dentistry" },
  { name: "Sodabeh Etminan", discipline: "General Dentistry" },
  { name: "Stephen Floe", discipline: "General Dentistry" },
  { name: "Sutton Lake", discipline: "General Dentistry" },
  { name: "A.J. Peak", discipline: "Miscellaneous" },
  { name: "Adrian McCovy", discipline: "Miscellaneous" },
  { name: "Alexander Einbinder", discipline: "Miscellaneous" },
  { name: "Alicia Kieffer", discipline: "Miscellaneous" },
  { name: "Allison Horn", discipline: "Miscellaneous" },
  { name: "Arthur W. Curley", discipline: "Miscellaneous" },
  { name: "Avi Weisfogel", discipline: "Miscellaneous" },
  { name: "Brad Billings", discipline: "Miscellaneous" },
  { name: "Burhan Syed", discipline: "Miscellaneous" },
  { name: "Cami Luljak", discipline: "Miscellaneous" },
  { name: "Chick Hoff", discipline: "Miscellaneous" },
  { name: "Colleen McFarlin", discipline: "Miscellaneous" },
  { name: "Cyrus Lee", discipline: "Miscellaneous" },
  { name: "Daniel Richards", discipline: "Miscellaneous" },
  { name: "Daniel Tataje", discipline: "Miscellaneous" },
  { name: "David Sopp", discipline: "Miscellaneous" },
  { name: "Dean Tassone", discipline: "Miscellaneous" },
  { name: "Dr. Alonso Carrasco-Labra", discipline: "Miscellaneous" },
  { name: "Dr. Aman S. Bhullar", discipline: "Miscellaneous" },
  { name: "Dr. Anthony Kofoworola-Kuti", discipline: "Miscellaneous" },
  { name: "Dr. Bijal Mehta", discipline: "Miscellaneous" },
  { name: "Dr. Brent Barta", discipline: "Miscellaneous" },
  { name: "Dr. Carol Lefebvre", discipline: "Miscellaneous" },
  { name: "Dr. Catrise Austin", discipline: "Miscellaneous" },
  { name: "Dr. Christopher Brendemuhl", discipline: "Miscellaneous" },
  { name: "Dr. David Wands", discipline: "Miscellaneous" },
  { name: "Dr. Effie Ioannidou", discipline: "Miscellaneous" },
  { name: "Dr. Eric C. Baker", discipline: "Miscellaneous" },
  { name: "Dr. Frank Tuminelli", discipline: "Miscellaneous" },
  { name: "Dr. Geith Kallas", discipline: "Miscellaneous" },
  { name: "Dr. George Tysowsky", discipline: "Miscellaneous" },
  { name: "Dr. Jason Genta", discipline: "Miscellaneous" },
  { name: "Dr. Kathryn Alderman", discipline: "Miscellaneous" },
  { name: "Dr. Lily Garcia", discipline: "Miscellaneous" },
  { name: "Dr. Loren Israelsen", discipline: "Miscellaneous" },
  { name: "Dr. Mahtab Sadrameli", discipline: "Miscellaneous" },
  { name: "Dr. Manu Chaudhry", discipline: "Miscellaneous" },
  { name: "Dr. Marie C. Schweinebraten", discipline: "Miscellaneous" },
  { name: "Dr. Martin Mendelson", discipline: "Miscellaneous" },
  { name: "Dr. Michael Reddy", discipline: "Miscellaneous" },
  { name: "Dr. Nimesh Patel", discipline: "Miscellaneous" },
  { name: "Dr. Robert S. Lewando", discipline: "Miscellaneous" },
  { name: "Dr. Ronald Saffar", discipline: "Miscellaneous" },
  { name: "Dr. Sam Bakuri", discipline: "Miscellaneous" },
  { name: "Dr. Sami Webb", discipline: "Miscellaneous" },
  { name: "Dr. Tarun Agarwal", discipline: "Miscellaneous" },
  { name: "Dr. Timothy McVaney", discipline: "Miscellaneous" },
  { name: "Dr. Tom Deans", discipline: "Miscellaneous" },
  { name: "Dr. Yahya Mansour", discipline: "Miscellaneous" },
  { name: "Emily Vanney", discipline: "Miscellaneous" },
  { name: "Francesca Pregano", discipline: "Miscellaneous" },
  { name: "Grant Bester", discipline: "Miscellaneous" },
  { name: "Greig Davis", discipline: "Miscellaneous" },
  { name: "Haim Haviv", discipline: "Miscellaneous" },
  { name: "Heather Foster", discipline: "Miscellaneous" },
  { name: "Hoss Said", discipline: "Miscellaneous" },
  { name: "Jackson Tralongo", discipline: "Miscellaneous" },
  { name: "Jaime Burks", discipline: "Miscellaneous" },
  { name: "Jason Coss", discipline: "Miscellaneous" },
  { name: "Jason Huml", discipline: "Miscellaneous" },
  { name: "Jason Korkus", discipline: "Miscellaneous" },
  { name: "Jason Mann", discipline: "Miscellaneous" },
  { name: "Jeffrey Tomcsik", discipline: "Miscellaneous" },
  { name: "Jessica Woods", discipline: "Miscellaneous" },
  { name: "Joe Feldsien", discipline: "Miscellaneous" },
  { name: "Judy Kay Mausolf", discipline: "Miscellaneous" },
  { name: "Kate Wilson", discipline: "Miscellaneous" },
  { name: "Katie Worth", discipline: "Miscellaneous" },
  { name: "Loren Israelsen", discipline: "Miscellaneous" },
  { name: "Louis Chmura", discipline: "Miscellaneous" },
  { name: "Mark Censoprano", discipline: "Miscellaneous" },
  { name: "Mark Lakis", discipline: "Miscellaneous" },
  { name: "Mark T. Murphy", discipline: "Miscellaneous" },
  { name: "Martin Mendelson", discipline: "Miscellaneous" },
  { name: "Matthew Simko", discipline: "Miscellaneous" },
  { name: "Michael Acierno", discipline: "Miscellaneous" },
  { name: "Michael Beschloss", discipline: "Miscellaneous" },
  { name: "Michelle Brumfield", discipline: "Miscellaneous" },
  { name: "Michelle Flesch", discipline: "Miscellaneous" },
  { name: "Mike Graham", discipline: "Miscellaneous" },
  { name: "Natalyn Lewis", discipline: "Miscellaneous" },
  { name: "Nick N. Khalili", discipline: "Miscellaneous" },
  { name: "Paul Goodman", discipline: "Miscellaneous" },
  { name: "Peter Swenson", discipline: "Miscellaneous" },
  { name: "Rashed Din", discipline: "Miscellaneous" },
  { name: "Ray Caruso", discipline: "Miscellaneous" },
  { name: "Robyn Gannaway", discipline: "Miscellaneous" },
  { name: "Rose House", discipline: "Miscellaneous" },
  { name: "Sabrina Sennett", discipline: "Miscellaneous" },
  { name: "Sara Mahmood", discipline: "Miscellaneous" },
  { name: "Shannon B. Williams", discipline: "Miscellaneous" },
  { name: "Stacia Edmond", discipline: "Miscellaneous" },
  { name: "Stacy Feffer-Farley", discipline: "Miscellaneous" },
  { name: "Stef Simich", discipline: "Miscellaneous" },
  { name: "Sundeep Rawal", discipline: "Miscellaneous" },
  { name: "Suzie Ramos", discipline: "Miscellaneous" },
  { name: "Terri Bradley", discipline: "Miscellaneous" },
  { name: "Tiffany Dufu", discipline: "Miscellaneous" },
  { name: "Trevor Maurer", discipline: "Miscellaneous" },
  { name: "Troy Aikman", discipline: "Miscellaneous" },
  { name: "Wayne Silverman", discipline: "Miscellaneous" },
  { name: "Allen Robinson", discipline: "Oral Surgery" },
  { name: "Avinash Bidra", discipline: "Oral Surgery" },
  { name: "Craig Misch", discipline: "Oral Surgery" },
  { name: "Dr. Antonia Kolokythas", discipline: "Oral Surgery" },
  { name: "Dr. Armand Bedrossian", discipline: "Oral Surgery" },
  { name: "Dr. Athena Goodarzi", discipline: "Oral Surgery" },
  { name: "Dr. Azam Saeed", discipline: "Oral Surgery" },
  { name: "Dr. Bach T. Le", discipline: "Oral Surgery" },
  { name: "Dr. Ben Kellum", discipline: "Oral Surgery" },
  { name: "Dr. Berfin K. Jacobs", discipline: "Oral Surgery" },
  { name: "Dr. Brian J. Jackson", discipline: "Oral Surgery" },
  { name: "Dr. Cara Minichetti", discipline: "Oral Surgery" },
  { name: "Dr. Carlos Aparicio", discipline: "Oral Surgery" },
  { name: "Dr. Clark Damon", discipline: "Oral Surgery" },
  { name: "Dr. Craig I. Aronson", discipline: "Oral Surgery" },
  { name: "Dr. Craig M. Misch", discipline: "Oral Surgery" },
  { name: "Dr. Dan Holtzclaw", discipline: "Oral Surgery" },
  { name: "Dr. Daniel Domingue", discipline: "Oral Surgery" },
  { name: "Dr. Daniel R. Cullum", discipline: "Oral Surgery" },
  { name: "Dr. David A. Fenton", discipline: "Oral Surgery" },
  { name: "Dr. David Resnick", discipline: "Oral Surgery" },
  { name: "Dr. Donald J. Provenzale", discipline: "Oral Surgery" },
  { name: "Dr. Donald P. Lewis Jr.", discipline: "Oral Surgery" },
  { name: "Dr. Drew Phillips", discipline: "Oral Surgery" },
  { name: "Dr. Duke Heller", discipline: "Oral Surgery" },
  { name: "Dr. E. Armand Bedrossian", discipline: "Oral Surgery" },
  { name: "Dr. Ed R. Kusek", discipline: "Oral Surgery" },
  { name: "Dr. Edgard El Chaar", discipline: "Oral Surgery" },
  { name: "Dr. Edmond Bedrossian", discipline: "Oral Surgery" },
  { name: "Dr. Faisal A. Quereshy", discipline: "Oral Surgery" },
  { name: "Dr. Gian Pietro Schincaglia", discipline: "Oral Surgery" },
  { name: "Dr. Hiroshi Hirata", discipline: "Oral Surgery" },
  { name: "Dr. Hussam Batal", discipline: "Oral Surgery" },
  { name: "Dr. Ihab Hanna", discipline: "Oral Surgery" },
  { name: "Dr. JB White", discipline: "Oral Surgery" },
  { name: "Dr. James Fetsch", discipline: "Oral Surgery" },
  { name: "Dr. James L. Rutkowski", discipline: "Oral Surgery" },
  { name: "Dr. James Nager", discipline: "Oral Surgery" },
  { name: "Dr. Jay C. Platt", discipline: "Oral Surgery" },
  { name: "Dr. Jay M. Neugarten", discipline: "Oral Surgery" },
  { name: "Dr. Jim Janakievski", discipline: "Oral Surgery" },
  { name: "Dr. Jimmie L. Harper Jr.", discipline: "Oral Surgery" },
  { name: "Dr. Joan Pi-Anfruns", discipline: "Oral Surgery" },
  { name: "Dr. John C. Minichetti", discipline: "Oral Surgery" },
  { name: "Dr. John F. Caccamese Jr.", discipline: "Oral Surgery" },
  { name: "Dr. John Minichetti", discipline: "Oral Surgery" },
  { name: "Dr. Joseph Leonetti", discipline: "Oral Surgery" },
  { name: "Dr. Kamal F. Busaidy", discipline: "Oral Surgery" },
  { name: "Dr. Katja Nelson", discipline: "Oral Surgery" },
  { name: "Dr. Keith Long", discipline: "Oral Surgery" },
  { name: "Dr. Kwan M. Lee", discipline: "Oral Surgery" },
  { name: "Dr. Lane T. Knight", discipline: "Oral Surgery" },
  { name: "Dr. Larry E. Stigall", discipline: "Oral Surgery" },
  { name: "Dr. Lawrence Nalitt", discipline: "Oral Surgery" },
  { name: "Dr. Lily Hu", discipline: "Oral Surgery" },
  { name: "Dr. Louis K. Rafetto", discipline: "Oral Surgery" },
  { name: "Dr. Luca Cordaro", discipline: "Oral Surgery" },
  { name: "Dr. Luiz Gonzaga", discipline: "Oral Surgery" },
  { name: "Dr. Manrique Fonseca", discipline: "Oral Surgery" },
  { name: "Dr. Mark Schlam", discipline: "Oral Surgery" },
  { name: "Dr. Michael A. Pikos", discipline: "Oral Surgery" },
  { name: "Dr. Michael Pikos", discipline: "Oral Surgery" },
  { name: "Dr. Michael Shulman", discipline: "Oral Surgery" },
  { name: "Dr. Nathan Doyel", discipline: "Oral Surgery" },
  { name: "Dr. Oded Bahat", discipline: "Oral Surgery" },
  { name: "Dr. Paul J. Schwartz", discipline: "Oral Surgery" },
  { name: "Dr. Paul S. Tiwana", discipline: "Oral Surgery" },
  { name: "Dr. Paulo Carvalho", discipline: "Oral Surgery" },
  { name: "Dr. Peter A. Vellis", discipline: "Oral Surgery" },
  { name: "Dr. Peter T. Green", discipline: "Oral Surgery" },
  { name: "Dr. Peter Wohrle", discipline: "Oral Surgery" },
  { name: "Dr. Peyman Raissi", discipline: "Oral Surgery" },
  { name: "Dr. Phil Walton", discipline: "Oral Surgery" },
  { name: "Dr. Rami Salloum", discipline: "Oral Surgery" },
  { name: "Dr. Ramsey Amin", discipline: "Oral Surgery" },
  { name: "Dr. Ricardo Mitrani", discipline: "Oral Surgery" },
  { name: "Dr. Robert J. Stanley", discipline: "Oral Surgery" },
  { name: "Dr. Robert W. Emery III", discipline: "Oral Surgery" },
  { name: "Dr. Rolf Ewers", discipline: "Oral Surgery" },
  { name: "Dr. Ryan Dunlop", discipline: "Oral Surgery" },
  { name: "Dr. Samantha A. Siranli", discipline: "Oral Surgery" },
  { name: "Dr. Sangiv I. Patel", discipline: "Oral Surgery" },
  { name: "Dr. Scott D. Ganz", discipline: "Oral Surgery" },
  { name: "Dr. Sean P. Edwards", discipline: "Oral Surgery" },
  { name: "Dr. Seth Chambers", discipline: "Oral Surgery" },
  { name: "Dr. Shahram Ghanaati", discipline: "Oral Surgery" },
  { name: "Dr. Shankar Iyer", discipline: "Oral Surgery" },
  { name: "Dr. Shuaib Malik", discipline: "Oral Surgery" },
  { name: "Dr. Stephanie W. Yeung", discipline: "Oral Surgery" },
  { name: "Dr. Sully Sullivan", discipline: "Oral Surgery" },
  { name: "Dr. Tara Aghaloo", discipline: "Oral Surgery" },
  { name: "Dr. Tarek Assi", discipline: "Oral Surgery" },
  { name: "Dr. Thomas D. Taylor", discipline: "Oral Surgery" },
  { name: "Dr. Tuan G. Bui", discipline: "Oral Surgery" },
  { name: "Dr. Vishy Broumand", discipline: "Oral Surgery" },
  { name: "Dr. Vivianne Chappuis", discipline: "Oral Surgery" },
  { name: "Dr. Waldemar Polido", discipline: "Oral Surgery" },
  { name: "Dr. Yolanda Natali Raico Gallardo", discipline: "Oral Surgery" },
  { name: "Joshua Edward Everts", discipline: "Oral Surgery" },
  { name: "Dr. Alvaro Blasi", discipline: "Orthodontics" },
  { name: "Dr. Benjamin Pliska", discipline: "Orthodontics" },
  { name: "Dr. James Mah", discipline: "Orthodontics" },
  { name: "Dr. Jasper Thoolen", discipline: "Orthodontics" },
  { name: "Dr. Jeffrey McClendon", discipline: "Orthodontics" },
  { name: "Dr. Katie Lee", discipline: "Orthodontics" },
  { name: "Dr. Larissa Trojan", discipline: "Orthodontics" },
  { name: "Dr. Marianna Evans", discipline: "Orthodontics" },
  { name: "Dr. Mark Lowe", discipline: "Orthodontics" },
  { name: "Dr. Melissa Shotell", discipline: "Orthodontics" },
  { name: "Dr. Michael Gunson", discipline: "Orthodontics" },
  { name: "Dr. Nada Souccar", discipline: "Orthodontics" },
  { name: "Dr. Renato Cocconi", discipline: "Orthodontics" },
  { name: "Dr. Roozbeh Khosravi", discipline: "Orthodontics" },
  { name: "Tracy Butler", discipline: "Orthodontics" },
  { name: "Dr. Amara Abreu-Serrano", discipline: "Pediatrics" },
  { name: "Dr. Emily Letran", discipline: "Pediatrics" },
  { name: "Dr. Issa Hanna", discipline: "Pediatrics" },
  { name: "Dr. Larry Brecht", discipline: "Pediatrics" },
  { name: "Dr. Mostafa Altalib", discipline: "Pediatrics" },
  { name: "Dr. Natasha Furchtgott", discipline: "Pediatrics" },
  { name: "Emily Letran", discipline: "Pediatrics" },
  { name: "Brody Hildebrand", discipline: "Periodontics" },
  { name: "CPT Andrew Egger", discipline: "Periodontics" },
  { name: "CPT Denise Cacho", discipline: "Periodontics" },
  { name: "CPT Justin Galliani", discipline: "Periodontics" },
  { name: "Capt Jess Cayetano", discipline: "Periodontics" },
  { name: "Capt Luke Seiler", discipline: "Periodontics" },
  { name: "Capt Victoria Wei", discipline: "Periodontics" },
  { name: "Dr. Acela Martinez", discipline: "Periodontics" },
  { name: "Dr. Adam Saltz", discipline: "Periodontics" },
  { name: "Dr. Alex Gillone", discipline: "Periodontics" },
  { name: "Dr. Alexandra Tsigarda", discipline: "Periodontics" },
  { name: "Dr. Algirdas Puisys", discipline: "Periodontics" },
  { name: "Dr. Allie Rascon", discipline: "Periodontics" },
  { name: "Dr. Amanda Finger Stadler", discipline: "Periodontics" },
  { name: "Dr. Andrea Ravida", discipline: "Periodontics" },
  { name: "Dr. Angela A. Palaiologou-Gallis", discipline: "Periodontics" },
  { name: "Dr. Anton Sculean", discipline: "Periodontics" },
  { name: "Dr. Arndt Guentsch", discipline: "Periodontics" },
  { name: "Dr. Beatriz Bezerra", discipline: "Periodontics" },
  { name: "Dr. Bindu Dukka", discipline: "Periodontics" },
  { name: "Dr. Bradley Ross", discipline: "Periodontics" },
  { name: "Dr. Brett Kessler", discipline: "Periodontics" },
  { name: "Dr. Bryan J. Frantz", discipline: "Periodontics" },
  { name: "Dr. Caitlin Darcey", discipline: "Periodontics" },
  { name: "Dr. Carlos Parra Carrasquer", discipline: "Periodontics" },
  { name: "Dr. Charles A. Powell", discipline: "Periodontics" },
  { name: "Dr. Christopher Petrush", discipline: "Periodontics" },
  { name: "Dr. Christopher R. Richardson", discipline: "Periodontics" },
  { name: "Dr. Chun-Teh Lee", discipline: "Periodontics" },
  { name: "Dr. Curry Leavitt", discipline: "Periodontics" },
  { name: "Dr. Daniel Buser", discipline: "Periodontics" },
  { name: "Dr. David A. Scott", discipline: "Periodontics" },
  { name: "Dr. David L. Cochran", discipline: "Periodontics" },
  { name: "Dr. David Lipton", discipline: "Periodontics" },
  { name: "Dr. David M. Kim", discipline: "Periodontics" },
  { name: "Dr. David P. Mathews", discipline: "Periodontics" },
  { name: "Dr. David T. Wu", discipline: "Periodontics" },
  { name: "Dr. Dennis Tarnow", discipline: "Periodontics" },
  { name: "Dr. Devorah Schwartz-Arad", discipline: "Periodontics" },
  { name: "Dr. Diego Velasquez-Plata", discipline: "Periodontics" },
  { name: "Dr. Dimitris N. Tatakis", discipline: "Periodontics" },
  { name: "Dr. Doaa Adel Khattab", discipline: "Periodontics" },
  { name: "Dr. Doug Dixon", discipline: "Periodontics" },
  { name: "Dr. Eduardo Lorenzana", discipline: "Periodontics" },
  { name: "Dr. Fadi Hasan", discipline: "Periodontics" },
  { name: "Dr. Flavia Q. Pirih", discipline: "Periodontics" },
  { name: "Dr. Frank A. Scannapieco", discipline: "Periodontics" },
  { name: "Dr. Frank Caputo", discipline: "Periodontics" },
  { name: "Dr. Frank Schwarz", discipline: "Periodontics" },
  { name: "Dr. Georgios A. Kotsakis", discipline: "Periodontics" },
  { name: "Dr. Georgios E. Romanos", discipline: "Periodontics" },
  { name: "Dr. Gilbert A. Fru", discipline: "Periodontics" },
  { name: "Dr. Giorgio Tabanella", discipline: "Periodontics" },
  { name: "Dr. Giovanni Zucchelli", discipline: "Periodontics" },
  { name: "Dr. Gustavo Avila Ortiz", discipline: "Periodontics" },
  { name: "Dr. Hatice Hasturk", discipline: "Periodontics" },
  { name: "Dr. Henry A. Foerster", discipline: "Periodontics" },
  { name: "Dr. Hom-Lay Wang", discipline: "Periodontics" },
  { name: "Dr. Homa H. Zadeh", discipline: "Periodontics" },
  { name: "Dr. Hsun-Liang Chan", discipline: "Periodontics" },
  { name: "Dr. Irina F. F. Dragan", discipline: "Periodontics" },
  { name: "Dr. Isabella Rocchietta", discipline: "Periodontics" },
  { name: "Dr. Istvan Urban", discipline: "Periodontics" },
  { name: "Dr. Jack G. Caton", discipline: "Periodontics" },
  { name: "Dr. James Anderson", discipline: "Periodontics" },
  { name: "Dr. Jeffrey A. Rossmann", discipline: "Periodontics" },
  { name: "Dr. Jennifer Bain", discipline: "Periodontics" },
  { name: "Dr. Jennifer H. Doobrow", discipline: "Periodontics" },
  { name: "Dr. Joan Otomo Corgel", discipline: "Periodontics" },
  { name: "Dr. Jonathan Esquivel", discipline: "Periodontics" },
  { name: "Dr. Jonathan Tai", discipline: "Periodontics" },
  { name: "Dr. Karim El Khouly", discipline: "Periodontics" },
  { name: "Dr. Karl Jepsen", discipline: "Periodontics" },
  { name: "Dr. Kevin Brown", discipline: "Periodontics" },
  { name: "Dr. Kumar Subramanian", discipline: "Periodontics" },
  { name: "Dr. Laura Williams", discipline: "Periodontics" },
  { name: "Dr. Lea Hachem", discipline: "Periodontics" },
  { name: "Dr. Liliana E. Aranguren", discipline: "Periodontics" },
  { name: "Dr. Lisa Taylor", discipline: "Periodontics" },
  { name: "Dr. Lorenzo Mordini", discipline: "Periodontics" },
  { name: "Dr. Lorenzo Tavelli", discipline: "Periodontics" },
  { name: "Dr. Luciana M. Shaddox", discipline: "Periodontics" },
  { name: "Dr. Maria Elisa Galarraga-Vinueza", discipline: "Periodontics" },
  { name: "Dr. Maria Emanuel Ryan", discipline: "Periodontics" },
  { name: "Dr. Maria Rodriguez", discipline: "Periodontics" },
  { name: "Dr. Markus Hürzeler", discipline: "Periodontics" },
  { name: "Dr. Massimo Costalonga", discipline: "Periodontics" },
  { name: "Dr. Matthew Fien", discipline: "Periodontics" },
  { name: "Dr. Mia L. Geisinger", discipline: "Periodontics" },
  { name: "Dr. Michael Cohen", discipline: "Periodontics" },
  { name: "Dr. Michael K. McGuire", discipline: "Periodontics" },
  { name: "Dr. Michael Richard Ragan", discipline: "Periodontics" },
  { name: "Dr. Michael Sterling", discipline: "Periodontics" },
  { name: "Dr. Miles Madison", discipline: "Periodontics" },
  { name: "Dr. Monica P. Gibson", discipline: "Periodontics" },
  { name: "Dr. Muhammad H. Saleh", discipline: "Periodontics" },
  { name: "Dr. Nikolaos Soldatos", discipline: "Periodontics" },
  { name: "Dr. Oscar González-Martin", discipline: "Periodontics" },
  { name: "Dr. Owais A. Farooqi", discipline: "Periodontics" },
  { name: "Dr. Panos N. Papapanou", discipline: "Periodontics" },
  { name: "Dr. Paul Fugazzotto", discipline: "Periodontics" },
  { name: "Dr. Paul S. Rosen", discipline: "Periodontics" },
  { name: "Dr. Peter C. Fritz", discipline: "Periodontics" },
  { name: "Dr. Philip Kang", discipline: "Periodontics" },
  { name: "Dr. Pierpaolo Cortellini", discipline: "Periodontics" },
  { name: "Dr. Purnima Kumar", discipline: "Periodontics" },
  { name: "Dr. Rachana Hegde", discipline: "Periodontics" },
  { name: "Dr. Rafael Siqueira", discipline: "Periodontics" },
  { name: "Dr. Ramzi V. Abou-Arraj", discipline: "Periodontics" },
  { name: "Dr. Richard Darveau", discipline: "Periodontics" },
  { name: "Dr. Rino Burkhardt", discipline: "Periodontics" },
  { name: "Dr. Robert A. Levine", discipline: "Periodontics" },
  { name: "Dr. Robert Levine", discipline: "Periodontics" },
  { name: "Dr. Rocio Beatriz Quinonez", discipline: "Periodontics" },
  { name: "Dr. Roger Arce", discipline: "Periodontics" },
  { name: "Dr. Samuel Lynch", discipline: "Periodontics" },
  { name: "Dr. Sandra Stuhr", discipline: "Periodontics" },
  { name: "Dr. Sascha Jovanovic", discipline: "Periodontics" },
  { name: "Dr. Satish S. Kumar", discipline: "Periodontics" },
  { name: "Dr. Sebastiano Andreana", discipline: "Periodontics" },
  { name: "Dr. Sejal Thacker", discipline: "Periodontics" },
  { name: "Dr. Sharon R. Bannister", discipline: "Periodontics" },
  { name: "Dr. Shayan Barootchi", discipline: "Periodontics" },
  { name: "Dr. Sonia Leziy", discipline: "Periodontics" },
  { name: "Dr. Stephanie Ganter", discipline: "Periodontics" },
  { name: "Dr. Steve D. Shufflebarger", discipline: "Periodontics" },
  { name: "Dr. Sukirth M. Ganesan", discipline: "Periodontics" },
  { name: "Dr. Susan Somerset", discipline: "Periodontics" },
  { name: "Dr. Theo Katsaros", discipline: "Periodontics" },
  { name: "Dr. Todd Scheyer", discipline: "Periodontics" },
  { name: "Dr. Vinay M. Bhide", discipline: "Periodontics" },
  { name: "Dr. Véronique Benhamou", discipline: "Periodontics" },
  { name: "Dr. Wenche S. Borgnakke", discipline: "Periodontics" },
  { name: "Dr. William V. Giannobile", discipline: "Periodontics" },
  { name: "Dr. William Victor Giannobile", discipline: "Periodontics" },
  { name: "Dr. Yota Stathopoulou", discipline: "Periodontics" },
  { name: "Dr. Yusuke Hamada", discipline: "Periodontics" },
  { name: "Dr. Zeeshan Sheikh", discipline: "Periodontics" },
  { name: "George Mandelaris", discipline: "Periodontics" },
  { name: "LT Jin Hwang", discipline: "Periodontics" },
  { name: "LT Nathan Kobold", discipline: "Periodontics" },
  { name: "LT Sofia Thompson", discipline: "Periodontics" },
  { name: "MAJ Toria Koutras", discipline: "Periodontics" },
  { name: "Prof. Anton Sculean", discipline: "Periodontics" },
  { name: "Prof. Frank Schwarz", discipline: "Periodontics" },
  { name: "Prof. Lior Shapira", discipline: "Periodontics" },
  { name: "Prof. Mariano Sanz", discipline: "Periodontics" },
  { name: "Prof. Nikolaos Donos", discipline: "Periodontics" },
  { name: "Prof. Tord Berglundh", discipline: "Periodontics" },
  { name: "Prof. Wim Teughels", discipline: "Periodontics" },
  { name: "Aleksandra Polcynsky", discipline: "Prosthodontics" },
  { name: "Arian B. Deutsch", discipline: "Prosthodontics" },
  { name: "Charles Goodacre", discipline: "Prosthodontics" },
  { name: "Darin Dichter", discipline: "Prosthodontics" },
  { name: "Douglas Benting", discipline: "Prosthodontics" },
  { name: "Dr. Agne Malisauskiene", discipline: "Prosthodontics" },
  { name: "Dr. Ahmet Orgev", discipline: "Prosthodontics" },
  { name: "Dr. Andrea Ricci", discipline: "Prosthodontics" },
  { name: "Dr. Andy Burton", discipline: "Prosthodontics" },
  { name: "Dr. Angel Garcia-Cañas", discipline: "Prosthodontics" },
  { name: "Dr. Anthony Sallustio", discipline: "Prosthodontics" },
  { name: "Dr. Avinash Bidra", discipline: "Prosthodontics" },
  { name: "Dr. Azadeh Amy Khajavi", discipline: "Prosthodontics" },
  { name: "Dr. Baldwin W. Marchack", discipline: "Prosthodontics" },
  { name: "Dr. Berfin Jacobs", discipline: "Prosthodontics" },
  { name: "Dr. Bruce G. Freund", discipline: "Prosthodontics" },
  { name: "Dr. Carlos de Carvalho", discipline: "Prosthodontics" },
  { name: "Dr. Christian Coachman", discipline: "Prosthodontics" },
  { name: "Dr. Christian Hart", discipline: "Prosthodontics" },
  { name: "Dr. David Norré", discipline: "Prosthodontics" },
  { name: "Dr. Dean Morton", discipline: "Prosthodontics" },
  { name: "Dr. Didier Dietschi", discipline: "Prosthodontics" },
  { name: "Dr. Douglas Benting", discipline: "Prosthodontics" },
  { name: "Dr. Ed McLaren", discipline: "Prosthodontics" },
  { name: "Dr. Eric Caron", discipline: "Prosthodontics" },
  { name: "Dr. Eric Van Dooren", discipline: "Prosthodontics" },
  { name: "Dr. Eva Boldridge", discipline: "Prosthodontics" },
  { name: "Dr. Frank M. Spear", discipline: "Prosthodontics" },
  { name: "Dr. Galip Gurel", discipline: "Prosthodontics" },
  { name: "Dr. George Arvanitis", discipline: "Prosthodontics" },
  { name: "Dr. Gerard J. Chiche", discipline: "Prosthodontics" },
  { name: "Dr. German O. Gallucci", discipline: "Prosthodontics" },
  { name: "Dr. Ghida Lawand", discipline: "Prosthodontics" },
  { name: "Dr. Giacomo Fabbri", discipline: "Prosthodontics" },
  { name: "Dr. Guillermo Chacon", discipline: "Prosthodontics" },
  { name: "Dr. Gustavo Giordani", discipline: "Prosthodontics" },
  { name: "Dr. Hamilton M. Sporborg", discipline: "Prosthodontics" },
  { name: "Dr. Heather Conrad", discipline: "Prosthodontics" },
  { name: "Dr. Hesham Nouh", discipline: "Prosthodontics" },
  { name: "Dr. Iñaki Gamborena", discipline: "Prosthodontics" },
  { name: "Dr. Janice Wang", discipline: "Prosthodontics" },
  { name: "Dr. Jason Kim", discipline: "Prosthodontics" },
  { name: "Dr. Jeff Rouse", discipline: "Prosthodontics" },
  { name: "Dr. John C. Kois", discipline: "Prosthodontics" },
  { name: "Dr. John Sorensen", discipline: "Prosthodontics" },
  { name: "Dr. Junji Tagami", discipline: "Prosthodontics" },
  { name: "Dr. Kimberly Schlam", discipline: "Prosthodontics" },
  { name: "Dr. Kostas Chochlidakis", discipline: "Prosthodontics" },
  { name: "Dr. Lawrence E. Brecht", discipline: "Prosthodontics" },
  { name: "Dr. Lorenzo Breschi", discipline: "Prosthodontics" },
  { name: "Dr. Marco Ferrari", discipline: "Prosthodontics" },
  { name: "Dr. Marco Veneziani", discipline: "Prosthodontics" },
  { name: "Dr. Mariam Margvelashvili-Malament", discipline: "Prosthodontics" },
  { name: "Dr. Mariano Polack", discipline: "Prosthodontics" },
  { name: "Dr. Mark Montana", discipline: "Prosthodontics" },
  { name: "Dr. Michael D. Scherer", discipline: "Prosthodontics" },
  { name: "Dr. Michael R. Andersen", discipline: "Prosthodontics" },
  { name: "Dr. Mijin Choi", discipline: "Prosthodontics" },
  { name: "Dr. Mostafa Altalibi", discipline: "Prosthodontics" },
  { name: "Dr. Naif Sinada", discipline: "Prosthodontics" },
  { name: "Dr. Nakul Rathi", discipline: "Prosthodontics" },
  { name: "Dr. Nitzan Bichacho", discipline: "Prosthodontics" },
  { name: "Dr. Oliver Pin-Harry", discipline: "Prosthodontics" },
  { name: "Dr. Panos Papaspyridakis", discipline: "Prosthodontics" },
  { name: "Dr. Panos Papaspyridakos", discipline: "Prosthodontics" },
  { name: "Dr. Paul Goodman", discipline: "Prosthodontics" },
  { name: "Dr. Ramon Gomez-Meda", discipline: "Prosthodontics" },
  { name: "Dr. Ricardo Kern", discipline: "Prosthodontics" },
  { name: "Dr. Roderick Stewart", discipline: "Prosthodontics" },
  { name: "Dr. Rooz Khosravi", discipline: "Prosthodontics" },
  { name: "Dr. Roxanna Esguerra", discipline: "Prosthodontics" },
  { name: "Dr. Ruben Arebalo", discipline: "Prosthodontics" },
  { name: "Dr. Sarah Lee", discipline: "Prosthodontics" },
  { name: "Dr. Sompop Bencharit", discipline: "Prosthodontics" },
  { name: "Dr. Stephen J. Chu", discipline: "Prosthodontics" },
  { name: "Dr. Steve Chu", discipline: "Prosthodontics" },
  { name: "Dr. Steve Parel", discipline: "Prosthodontics" },
  { name: "Dr. Steve Sadowsky", discipline: "Prosthodontics" },
  { name: "Dr. Steven Morgano", discipline: "Prosthodontics" },
  { name: "Dr. Swati Agnihotri", discipline: "Prosthodontics" },
  { name: "Dr. Taiseer Sulaiman", discipline: "Prosthodontics" },
  { name: "Dr. Tammeka Nickleberry", discipline: "Prosthodontics" },
  { name: "Dr. Taylor Jean Manalili", discipline: "Prosthodontics" },
  { name: "Dr. Thaisa Bordin", discipline: "Prosthodontics" },
  { name: "Dr. Timothy A. Hess", discipline: "Prosthodontics" },
  { name: "Dr. Tony Rotondo", discipline: "Prosthodontics" },
  { name: "Dr. Van Ramos Jr.", discipline: "Prosthodontics" },
  { name: "Dr. Wael Att", discipline: "Prosthodontics" },
  { name: "Dr. Wei-Shao Lin", discipline: "Prosthodontics" },
  { name: "Dr. Will Martin", discipline: "Prosthodontics" },
  { name: "Dr. William Liang", discipline: "Prosthodontics" },
  { name: "Dr. Yu Zhang", discipline: "Prosthodontics" },
  { name: "Ed McLaren", discipline: "Prosthodontics" },
  { name: "Eva Boldridge", discipline: "Prosthodontics" },
  { name: "Frank J. Tuminelli", discipline: "Prosthodontics" },
  { name: "German Gallucci", discipline: "Prosthodontics" },
  { name: "German Gallucci", discipline: "Prosthodontics" },
  { name: "John Sorensen", discipline: "Prosthodontics" },
  { name: "Michael R. Andersen", discipline: "Prosthodontics" },
  { name: "Rafael Pinzon", discipline: "Prosthodontics" },
  { name: "Rooz Khosravi", discipline: "Prosthodontics" },
  { name: "Roxanna Esguerra", discipline: "Prosthodontics" },
  { name: "Ruben Arebalo", discipline: "Prosthodontics" },
  { name: "Steve Chu", discipline: "Prosthodontics" },
  { name: "Steven Morgano", discipline: "Prosthodontics" },
  { name: "Taiseer Sulaiman", discipline: "Prosthodontics" },
  { name: "Taylor Jean Manalili", discipline: "Prosthodontics" },
  { name: "Timothy A. Hess", discipline: "Prosthodontics" },
  { name: "Van Ramos", discipline: "Prosthodontics" },
  { name: "Wei-Shao Lin", discipline: "Prosthodontics" },
];
