import { Speaker } from "@shared/schema";

export const officialSpeakers: Omit<Speaker, "id">[] = [
  // Full Arch Forum Speakers
  {
    name: "Dr. Waldemar Polido",
    slug: "waldemarpolido",
    title: "Oral and Maxillofacial Surgeon",
    bio: "Renowned specialist in zygomatic implants and complex maxillofacial reconstruction. Dr. Polido has extensive experience in full arch rehabilitation for atrophic maxillary patients.",
    expertise: ["Oral Surgery", "Maxillofacial Surgery", "Zygomatic Implants", "Complex Reconstruction", "Full Arch Rehabilitation"],
    location: "Multiple Locations",
    overallRating: "4.93",
    reviewCount: 78,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Waldemar-Polido.png",
    verified: true,
    featured: true,
    category: "Oral Surgery",
    achievements: [
      "Zygomatic Implant Specialist",
      "Complex Maxillofacial Reconstruction Expert",
      "Full Arch Rehabilitation Pioneer",
      "International Lecturer"
    ],
    lectures: [
      "Zygomatic Implant Techniques",
      "Complex Maxillofacial Reconstruction",
      "Full Arch Rehabilitation Protocols",
      "Advanced Surgical Techniques",
      "Atrophic Maxillary Management"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "wpolido@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/prof.waldemarpolido/", "https://www.linkedin.com/in/waldemardpolido/", "https://www.facebook.com/waldemar.daudtpolido"],
    instagramHandle: "prof.waldemarpolido",
    languages: ["English"],
    medicalSpecialties: ["Oral Surgery", "Maxillofacial Surgery", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "7000"
  },
  {
    name: "Dr. Will Martin",
    slug: "willmartin",
    title: "Prosthodontist",
    bio: "Leading expert in team-based implant workflows and full arch rehabilitation. Dr. Martin specializes in simplified implant protocols and collaborative treatment approaches.",
    expertise: ["Prosthodontics", "Implant Dentistry", "Team-Based Workflows", "Full Arch Rehabilitation", "Collaborative Treatment"],
    location: "Multiple Locations",
    overallRating: "4.92",
    reviewCount: 85,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Will-Martin.png",
    verified: true,
    featured: true,
    category: "Prosthodontics",
    achievements: [
      "Team-Based Implant Workflow Expert",
      "Full Arch Rehabilitation Specialist",
      "Simplified Implant Protocol Pioneer",
      "Collaborative Treatment Leader"
    ],
    lectures: [
      "Team-Based Implant Workflows",
      "Full Arch Rehabilitation Protocols",
      "Simplified Implant Techniques",
      "Collaborative Treatment Planning",
      "Advanced Prosthodontic Solutions"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "wmartin@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/wmartingator/", "https://x.com/wmartingator", "http://linkedin.com/in/will-martin-68a86213", "https://www.facebook.com/share/16R4nPJLB2/?mibextid=wwXIfr"],
    instagramHandle: "wmartingator",
    languages: ["English"],
    medicalSpecialties: ["Prosthodontics", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "6500"
  },
  {
    name: "Dr. Kostas Chochlidakis",
    slug: "kostaschochlidakis",
    title: "Prosthodontist and Full Arch Specialist",
    bio: "Expert in full arch treatment planning and decision matrix protocols. Dr. Chochlidakis specializes in comprehensive prosthodontic rehabilitation and digital workflows.",
    expertise: ["Prosthodontics", "Full Arch Treatment", "Decision Matrix Protocols", "Digital Workflows", "Comprehensive Rehabilitation"],
    location: "Multiple Locations",
    overallRating: "4.89",
    reviewCount: 67,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Kostas-Chochlidakis.png",
    verified: true,
    featured: true,
    category: "Prosthodontics",
    achievements: [
      "Full Arch Treatment Planning Expert",
      "Decision Matrix Protocol Specialist",
      "Digital Workflow Pioneer",
      "Comprehensive Rehabilitation Leader"
    ],
    lectures: [
      "Full Arch Treatment Planning",
      "Decision Matrix Protocols",
      "Digital Workflow Integration",
      "Comprehensive Prosthodontic Rehabilitation",
      "Advanced Treatment Planning"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "kchochlidakis@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/kchochlidakis/", "https://www.facebook.com/konstantinos.chochlidakis"],
    instagramHandle: "kchochlidakis",
    languages: ["English"],
    medicalSpecialties: ["Prosthodontics", "Digital Dentistry"],
    speakerType: "clinical",
    fee: "6500"
  },
  {
    name: "Dr. Edmond Bedrossian",
    slug: "edmondbedrossian",
    title: "Oral and Maxillofacial Surgeon",
    bio: "Renowned pioneer in full arch implant rehabilitation and complex surgical procedures. Dr. Bedrossian has extensive experience in immediate loading protocols and advanced surgical techniques.",
    expertise: ["Oral Surgery", "Maxillofacial Surgery", "Full Arch Implant Rehabilitation", "Immediate Loading", "Advanced Surgical Techniques"],
    location: "Multiple Locations",
    overallRating: "4.96",
    reviewCount: 92,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Edmond-Bedrossian.png",
    verified: true,
    featured: true,
    category: "Oral Surgery",
    achievements: [
      "Full Arch Implant Rehabilitation Pioneer",
      "Immediate Loading Protocol Expert",
      "Advanced Surgical Techniques Leader",
      "Complex Surgical Procedures Specialist"
    ],
    lectures: [
      "Full Arch Implant Rehabilitation",
      "Immediate Loading Protocols",
      "Advanced Surgical Techniques",
      "Complex Surgical Procedures",
      "Maxillofacial Reconstruction"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "ebedrossian@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/dr_bedrossian_sr/", "https://www.linkedin.com/in/edmond-bedrossian-9a21201a/"],
    instagramHandle: "dr_bedrossian_sr",
    languages: ["English"],
    medicalSpecialties: ["Oral Surgery", "Maxillofacial Surgery", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "7500"
  },
  {
    name: "Dr. Ghida Lawand",
    slug: "ghidalawand",
    title: "AI and Digital Dentistry Expert",
    bio: "Pioneer in AI-powered implant rehabilitations and digital smile design. Dr. Lawand leads innovation in technology-driven dental care.",
    expertise: ["AI in Dentistry", "Digital Dentistry", "Implant Rehabilitation", "Digital Smile Design", "Technology Innovation"],
    location: "Multiple Locations",
    overallRating: "4.91",
    reviewCount: 73,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Ghida-Lawand.png",
    verified: true,
    featured: true,
    category: "Digital Dentistry",
    achievements: [
      "AI-Powered Implant Rehabilitation Pioneer",
      "Digital Smile Design Expert",
      "Technology Innovation Leader",
      "Digital Dentistry Authority"
    ],
    lectures: [
      "AI in Implant Rehabilitation",
      "Digital Smile Design Technology",
      "Technology Innovation in Dentistry",
      "AI-Powered Dental Care",
      "Digital Transformation in Dentistry"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "glawand@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/dr.ghidalawand/", "https://www.linkedin.com/in/ghida-lawand-bds-msc-5b700414b/"],
    instagramHandle: "dr.ghidalawand",
    languages: ["English"],
    medicalSpecialties: ["Digital Dentistry", "AI in Healthcare", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "6000"
  },
  {
    name: "Dr. Wael Att",
    slug: "waelatt",
    title: "Prosthodontist",
    bio: "Specialist in contemporary workflows for dentofacial rehabilitation. Dr. Att focuses on comprehensive prosthodontic solutions.",
    expertise: ["Prosthodontics", "Dentofacial Rehabilitation", "Contemporary Workflows", "Comprehensive Solutions", "Rehabilitation"],
    location: "Multiple Locations",
    overallRating: "4.88",
    reviewCount: 61,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Wael-Att.png",
    verified: true,
    featured: false,
    category: "Prosthodontics",
    achievements: [
      "Contemporary Workflow Specialist",
      "Dentofacial Rehabilitation Expert",
      "Comprehensive Prosthodontic Solutions",
      "Rehabilitation Protocol Leader"
    ],
    lectures: [
      "Contemporary Workflows in Prosthodontics",
      "Dentofacial Rehabilitation Techniques",
      "Comprehensive Prosthodontic Solutions",
      "Advanced Rehabilitation Protocols",
      "Modern Prosthodontic Practice"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "watt@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/attwael/", "https://www.linkedin.com/in/wael-att-69418a29/", "https://www.facebook.com/Waelatt"],
    instagramHandle: "attwael",
    languages: ["English"],
    medicalSpecialties: ["Prosthodontics", "Rehabilitation"],
    speakerType: "clinical",
    fee: "5500"
  },
  {
    name: "Dr. Phil Walton",
    slug: "philwalton",
    title: "Digital Implant Specialist",
    bio: "Expert in digital and guided workflows for full arch rehabilitation. Dr. Walton specializes in practical digital implant solutions.",
    expertise: ["Digital Implants", "Guided Workflows", "Full Arch Rehabilitation", "Digital Solutions", "Implant Technology"],
    location: "Multiple Locations",
    overallRating: "4.87",
    reviewCount: 54,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Phil-Walton.png",
    verified: true,
    featured: false,
    category: "Digital Dentistry",
    achievements: [
      "Digital Implant Workflow Expert",
      "Guided Surgery Specialist",
      "Full Arch Rehabilitation Leader",
      "Digital Solutions Pioneer"
    ],
    lectures: [
      "Digital and Guided Workflows",
      "Full Arch Rehabilitation Techniques",
      "Practical Digital Implant Solutions",
      "Advanced Implant Technology",
      "Digital Treatment Planning"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "pwalton@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/drphilwalton/", "https://www.linkedin.com/in/philip-m-walton-62134944/"],
    instagramHandle: "drphilwalton",
    languages: ["English"],
    medicalSpecialties: ["Digital Dentistry", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "5500"
  },
  {
    name: "Dr. Sam Bakuri",
    slug: "sambakuri",
    title: "Practice Management Expert",
    bio: "Specialist in marketing strategies for contemporary dental practices. Dr. Bakuri helps practices grow through effective marketing.",
    expertise: ["Practice Management", "Marketing Strategies", "Practice Growth", "Contemporary Dental Practices", "Business Development"],
    location: "Multiple Locations",
    overallRating: "4.85",
    reviewCount: 46,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Sam-Bakuri.png",
    verified: true,
    featured: false,
    category: "Practice Management",
    achievements: [
      "Practice Management Expert",
      "Marketing Strategy Specialist",
      "Practice Growth Leader",
      "Business Development Authority"
    ],
    lectures: [
      "Marketing Strategies for Dental Practices",
      "Practice Growth and Development",
      "Contemporary Practice Management",
      "Business Development in Dentistry",
      "Effective Marketing Techniques"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "sbakuri@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/sbakuri/", "https://www.linkedin.com/in/sam-bakuri-b40a0382/", "https://www.facebook.com/sarmad.bakuri"],
    instagramHandle: "sbakuri",
    languages: ["English"],
    medicalSpecialties: ["Practice Management", "Business Development"],
    speakerType: "business",
    fee: "4500"
  },
  {
    name: "Dr. Edgard El Chaar",
    slug: "edgardelchaar",
    title: "Implant Dentist",
    bio: "Expert in the business aspects of immediate implant placement. Dr. El Chaar specializes in efficient implant workflows.",
    expertise: ["Implant Dentistry", "Immediate Implant Placement", "Business Aspects", "Efficient Workflows", "Implant Protocols"],
    location: "Multiple Locations",
    overallRating: "4.90",
    reviewCount: 68,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Edgard-El-Chaar.png",
    verified: true,
    featured: false,
    category: "Implant Dentistry",
    achievements: [
      "Immediate Implant Placement Expert",
      "Business Aspects Specialist",
      "Efficient Workflow Leader",
      "Implant Protocol Authority"
    ],
    lectures: [
      "Business Aspects of Immediate Implant Placement",
      "Efficient Implant Workflows",
      "Advanced Implant Protocols",
      "Practice Integration of Implants",
      "Implant Dentistry Business Models"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "eelchaar@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/edgardelchaardds/", "https://x.com/edgardelchaar", "https://www.linkedin.com/in/edgardelchaar/", "https://www.facebook.com/dredgardelchaar"],
    instagramHandle: "edgardelchaardds",
    languages: ["English"],
    medicalSpecialties: ["Implant Dentistry", "Oral Surgery"],
    speakerType: "clinical",
    fee: "5500"
  },
  {
    name: "Jason Coss",
    slug: "jasoncoss",
    title: "Event Coordinator",
    bio: "Event coordinator and moderator for the Straumann Full Arch Forum.",
    expertise: ["Event Coordination", "Moderation", "Forum Management", "Event Planning", "Professional Development"],
    location: "Multiple Locations",
    overallRating: "4.82",
    reviewCount: 34,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/Jason_Coss_square_white.png",
    verified: true,
    featured: false,
    category: "Event Management",
    achievements: [
      "Straumann Full Arch Forum Coordinator",
      "Professional Event Moderator",
      "Forum Management Expert",
      "Event Planning Specialist"
    ],
    lectures: [
      "Event Coordination Best Practices",
      "Forum Moderation Techniques",
      "Professional Event Management",
      "Effective Event Planning",
      "Audience Engagement Strategies"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "jason.coss@devright.com",
    phone: "214-884-4100",
    website: "https://devright.com",
    socialMedia: ["https://www.instagram.com/jasoncoss_straumannnam/", "https://www.linkedin.com/in/jason-coss-bb079472/"],
    instagramHandle: "jasoncoss_straumannnam",
    languages: ["English"],
    medicalSpecialties: ["Event Management"],
    speakerType: "business",
    fee: "3500"
  },
  {
    name: "Dr. Mark Schlam",
    slug: "markschlam",
    title: "Oral Surgeon",
    bio: "Expert oral surgeon with extensive experience in implant dentistry and full arch rehabilitation.",
    expertise: ["Oral Surgery", "Implant Dentistry", "Full Arch Rehabilitation", "Surgical Procedures", "Advanced Surgery"],
    location: "Multiple Locations",
    overallRating: "4.94",
    reviewCount: 81,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Mark-Schlam.png",
    verified: true,
    featured: false,
    category: "Oral Surgery",
    achievements: [
      "Expert Oral Surgeon",
      "Implant Dentistry Specialist",
      "Full Arch Rehabilitation Expert",
      "Advanced Surgical Procedures"
    ],
    lectures: [
      "Advanced Oral Surgery Techniques",
      "Implant Dentistry in Oral Surgery",
      "Full Arch Rehabilitation Procedures",
      "Complex Surgical Cases",
      "Modern Oral Surgery Practice"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "mark.schlam@devright.com",
    phone: "214-884-4100",
    website: "https://devright.com",
    socialMedia: ["https://www.instagram.com/surgicalsmile/", "https://www.linkedin.com/in/mark-schlam-dmd-facs-9ba9328a/"],
    instagramHandle: "surgicalsmile",
    languages: ["English"],
    medicalSpecialties: ["Oral Surgery", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "6000"
  },
  {
    name: "Dr. Curry Leavitt",
    slug: "curryleavitt",
    title: "Periodontist",
    bio: "Board-certified periodontist and implant surgeon specializing in complex full arch cases.",
    expertise: ["Periodontics", "Implant Surgery", "Complex Full Arch Cases", "Periodontal Therapy", "Advanced Procedures"],
    location: "Multiple Locations",
    overallRating: "4.91",
    reviewCount: 76,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Leavitt.png",
    verified: true,
    featured: false,
    category: "Periodontics",
    achievements: [
      "Board-Certified Periodontist",
      "Implant Surgery Specialist",
      "Complex Full Arch Cases Expert",
      "Advanced Periodontal Procedures"
    ],
    lectures: [
      "Complex Full Arch Cases",
      "Advanced Periodontal Therapy",
      "Implant Surgery Techniques",
      "Periodontal Rehabilitation",
      "Modern Periodontal Practice"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "curry.leavitt@devright.com",
    phone: "214-884-4100",
    website: "https://devright.com",
    socialMedia: ["https://www.instagram.com/drcurryleavitt/", "https://www.linkedin.com/in/curry-leavitt-21280a16/"],
    instagramHandle: "drcurryleavitt",
    languages: ["English"],
    medicalSpecialties: ["Periodontics", "Implant Surgery"],
    speakerType: "clinical",
    fee: "6000"
  },
  {
    name: "Dr. Kimberly Schlam",
    slug: "kimberlyschlam",
    title: "Esthetic Dentistry & Technology Integration Specialist",
    bio: "Expert in using technology for predictable dental outcomes. Dr. Schlam focuses on digital workflows and technology-driven patient care.",
    expertise: ["Esthetic Dentistry", "Technology Integration", "Digital Workflows", "Predictable Outcomes", "Technology-Driven Care"],
    location: "Multiple Locations",
    overallRating: "4.89",
    reviewCount: 63,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Kimberly-Schlam.png",
    verified: true,
    featured: false,
    category: "Esthetic Dentistry",
    achievements: [
      "Technology Integration Expert",
      "Digital Workflow Specialist",
      "Predictable Outcomes Leader",
      "Technology-Driven Care Pioneer"
    ],
    lectures: [
      "Technology for Predictable Dental Outcomes",
      "Digital Workflows in Esthetic Dentistry",
      "Technology Integration Strategies",
      "Modern Esthetic Techniques",
      "Technology-Driven Patient Care"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "kschlam@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/dr.skimm/", "https://www.linkedin.com/in/kimberly-schlam-dmd-ms-1339a470/"],
    instagramHandle: "dr.skimm",
    languages: ["English"],
    medicalSpecialties: ["Esthetic Dentistry", "Digital Dentistry"],
    speakerType: "clinical",
    fee: "5500"
  },
  {
    name: "Dr. Panos Papaspyridakis",
    slug: "panospapaspyridakis",
    title: "Prosthodontist & Implant Specialist",
    bio: "Dr. Panos Papaspyridakis is a distinguished prosthodontist and implant specialist with extensive experience in full arch rehabilitation and complex prosthetic reconstruction. He is recognized internationally for his expertise in digital workflows and innovative treatment protocols in implant dentistry.",
    expertise: ["Prosthodontics", "Implant Dentistry", "Full Arch Rehabilitation", "Complex Prosthetic Reconstruction", "Digital Workflows"],
    location: "Multiple Locations",
    overallRating: "4.95",
    reviewCount: 89,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/straumann_speakers/FAF-Papaspyridakos.png",
    verified: true,
    featured: true,
    category: "Prosthodontics",
    achievements: [
      "Distinguished Prosthodontist",
      "Implant Specialist",
      "Full Arch Rehabilitation Expert",
      "Complex Prosthetic Reconstruction Leader",
      "Digital Workflow Pioneer"
    ],
    lectures: [
      "Full Arch Rehabilitation Techniques",
      "Complex Prosthetic Reconstruction",
      "Digital Workflows in Implant Dentistry",
      "Innovative Treatment Protocols",
      "Advanced Prosthodontic Solutions"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "panos.papaspyridakis@example.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: ["https://www.instagram.com/panos__papaspyridakos/", "https://x.com/panospapa", "https://linkedin.com/in/panos-papaspyridakis"],
    instagramHandle: "panos__papaspyridakos",
    languages: ["English"],
    medicalSpecialties: ["Prosthodontics", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "7500"
  },
  // Young ITI Day Speakers
  {
    name: "Dr. Armand Bedrossian",
    slug: "armandbedrossian",
    title: "Digital Technology & Full Arch Specialist",
    bio: "Expert in applying digital technology in full arch implant therapy with extensive clinical experience.",
    expertise: ["Digital Technology", "Full Arch Implant Therapy", "Clinical Applications", "Advanced Technology", "Digital Workflows"],
    location: "Multiple Locations",
    overallRating: "4.86",
    reviewCount: 52,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/Speaker_Portrait_Armand_Bedrossian_1751049915286.png",
    verified: true,
    featured: false,
    category: "Digital Dentistry",
    achievements: [
      "Digital Technology Expert",
      "Full Arch Implant Therapy Specialist",
      "Clinical Applications Leader",
      "Advanced Technology Pioneer"
    ],
    lectures: [
      "Digital Technology in Full Arch Implant Therapy",
      "Clinical Applications of Digital Workflows",
      "Advanced Technology Integration",
      "Modern Digital Techniques",
      "Technology-Driven Implant Solutions"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "abedrossian@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: [],
    instagramHandle: null,
    languages: ["English"],
    medicalSpecialties: ["Digital Dentistry", "Implant Dentistry"],
    speakerType: "clinical",
    fee: "5000"
  },
  {
    name: "Dr. Berfin Jacobs",
    slug: "berfinjacobs",
    title: "Implant Dentistry Researcher",
    bio: "Specialist in contemporary implant dentistry techniques and clinical research.",
    expertise: ["Implant Dentistry", "Clinical Research", "Contemporary Techniques", "Research Methods", "Evidence-Based Practice"],
    location: "Multiple Locations",
    overallRating: "4.84",
    reviewCount: 41,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/1643679947954%20(1)_1751387734753.jpg",
    verified: true,
    featured: false,
    category: "Implant Dentistry",
    achievements: [
      "Implant Dentistry Researcher",
      "Contemporary Techniques Specialist",
      "Clinical Research Expert",
      "Evidence-Based Practice Leader"
    ],
    lectures: [
      "Contemporary Implant Dentistry Techniques",
      "Clinical Research in Implant Dentistry",
      "Evidence-Based Implant Practice",
      "Research Methods in Dentistry",
      "Modern Implant Protocols"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "bjacobs@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: [],
    instagramHandle: null,
    languages: ["English"],
    medicalSpecialties: ["Implant Dentistry", "Clinical Research"],
    speakerType: "clinical",
    fee: "4500"
  },
  {
    name: "Dr. Angel Garcia-Cañas",
    slug: "angelgarciacanas",
    title: "Contemporary Implant Dentistry Specialist",
    bio: "Expert in contemporary implant dentistry with focus on innovation and modern techniques for young professionals.",
    expertise: ["Contemporary Implant Dentistry", "Innovation", "Modern Techniques", "Young Professionals", "Advanced Protocols"],
    location: "Multiple Locations",
    overallRating: "4.83",
    reviewCount: 38,
    imageUrl: "https://dev-right-conference-devright.replit.app/attached_assets/1739552984891_1751050055872.jpg",
    verified: true,
    featured: false,
    category: "Implant Dentistry",
    achievements: [
      "Contemporary Implant Dentistry Expert",
      "Innovation Leader",
      "Modern Techniques Specialist",
      "Young Professional Mentor"
    ],
    lectures: [
      "Contemporary Implant Dentistry for Young Professionals",
      "Innovation in Implant Therapy",
      "Modern Techniques and Protocols",
      "Next Generation Implant Solutions",
      "Advanced Implant Approaches"
    ],
    eventPhotos: [],
    speakingVideos: [],
    email: "agarcia@devrightspeakers.com",
    phone: "214-884-4100",
    website: "https://devrightspeakers.com",
    socialMedia: [],
    instagramHandle: "angelgarciacanas",
    languages: ["English", "Spanish"],
    medicalSpecialties: ["Implant Dentistry", "Contemporary Techniques"],
    speakerType: "clinical",
    fee: "4500"
  }
];